@Host = http://localhost:3000


POST {{Host}}/api/users
Content-Type: application/json

{
  "email": "min@example.org",
  "username": "min"
}

###############
# @name login
POST {{Host}}/api/login
Content-Type: application/json

{
  "email": "john@example.org"
}

####################
GET {{Host}}/api/auth_user
Authorization: Bearer KCBhlZ4bTKqgFLGbKKJdJX7y1LToB2TBNEhoEoGi7wjoIXch4f24XsQHlDMWCy

######################

GET {{Host}}/api/users?search=&first=&after=
Authorization: Bearer {{login.response.body.token}}

#######################
GET {{Host}}/api/users/john
Authorization: Bearer {{login.response.body.token}}

###

PUT {{Host}}/api/auth_user/avatar
Authorization: Bearer {{login.response.body.token}}
Content-Type: image/png

< asset/sample.jpg

#################
POST {{Host}}/api/users/jane/toggle_follow
Authorization: Bearer {{login.response.body.token}}

###
GET {{Host}}/api/users/john/followers?first=&after=
Authorization: Bearer {{login.response.body.token}}

###
GET {{Host}}/api/users/jane/followees?first=&after=
Authorization: Bearer {{login.response.body.token}}

###
POST {{Host}}/api/posts
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "content": "neweeeee post",
  "spoilerOf": "show name here",
  "nsfw": true
}

###
GET {{Host}}/api/users/john/posts?last=3&before=
Authorization: Bearer {{login.response.body.token}}

###
GET {{Host}}/api/posts/3
Authorization: Bearer {{login.response.body.token}}

###
POST {{Host}}/api/posts/1/toggle_like
Authorization: Bearer {{login.response.body.token}}

###
GET {{Host}}/api/timeline?last=&before=535259992687443969
Authorization: Bearer {{login.response.body.token}}