DROP DATABASE IF EXISTS sodam
CASCADE;
CREATE DATABASE
IF NOT EXISTS sodam;
SET
DATABASE = sodam;

CREATE TABLE
IF NOT EXISTS users
(
	id SERIAL NOT NULL PRIMARY KEY,
	email VARCHAR NOT NULL UNIQUE,
	username VARCHAR NOT NULL UNIQUE
);